const { format } = require('date-fns')

class CreateDetalheLoteSegmentoP {
    run() {
        const detalheLoteSegmentoP = ''

        const obj = {    
            codigoBanco: '104',
            loteServicoHeaderArquivo: '0001',
            tipoRegistro: '3',
            sequencialRegistroLote: '1'.padEnd(5, '0'),
            codSegmentoRegistroDetalhe: 'P',
            febrabanCnabExclusivo: ' ',
            codMovimentoRemessa: '01',
            codAgencia: '8572'.padStart(5,'0'),
            digitoVerificadorAgencia: ''.padStart(1, ' '),
            nrContaBancaria: '05684'.padStart(12, '0'),
            digitoVerificadorConta: '7',
            digitoVerificadorAgenciaConta: ''.padStart(1, ' '),
            nossoNumero:'777777'.padEnd(20, '0'),
            codCarteira: '1',
            formaCadastroTituloBanco: '1',
            tipoDocumento: '1',
            tipoEmissaoBoletoPgto: '2',
            tipoDestribuicaoBoletoPgto: '2',
            nrIdentificacaoBoletoCobranca: '882789'.padStart(15, '0'),
            dtVencimentoTitulo: format(new Date(), 'ddMMyyyy'),
            valorNominalTitulo: '3742.87'.replace('.', '').padStart(15, '0'),
            agenciaCobranca: '0'.padStart(5, '0'),
            digitoVerificadorAgenciaCobranca: ''.padStart(1, ' '),
            especieTitulo: '03',
            aceiteTitulo: 'N',
            dtEmissaoTitulo: format(new Date(), 'ddMMyyyy'),
            codJurosMora: '1',
            dataJurosMora: ''.padStart(8, '0'),
            jurosMoraPorDia: '0.51'.replace('.', '').padStart(15, 0),
            codDesconto1: '0',
            dataDesconto1: ''.padStart(8, '0'),
            valorOuPercentualConcedido: '0'.padStart(15, 0),
            valorIofRecolhido: '0'.padStart(15, 0),
            valorAbatimento: '0'.padStart(15, 0),
            identificacaoTituloEmpresa: '0297899805907'.padStart(25, '0'),
            codigoParaProtesto: '3',
            numeroDiaProtesto: '00',
            codigoBaixaDevolucao: '1',
            numeroDiaBaixaDevolucao: '60'.padStart(3, '0'),
            codMoeda: '09',
            nrContrato: '0'.padStart(10, '0'),
            febrabanCnabExclusivo2: ' ',
            codAgencia: '8572'.padStart(5,'0'),
            digitoVerificadorAgencia: ''.padStart(1, ' '),
            nrContaBancaria: '05684'.padStart(12, '0'),
            digitoVerificadorConta: '7',
            digitoVerificadorAgenciaConta: ''.padStart(1, ' '),
            nossoNumero:'777777'.padEnd(20, '0'),
            codCarteira: '1',
            formaCadastroTituloBanco: '1',
            tipoDocumento: '1',
            tipoEmissaoBoletoPgto: '2',
            tipoDestribuicaoBoletoPgto: '2',
            nrIdentificacaoBoletoCobranca: '882789'.padStart(15, '0'),
            dtVencimentoTitulo: format(new Date(), 'ddMMyyyy'),
            valorNominalTitulo: '3742.87'.replace('.', '').padStart(15, '0'),
            agenciaCobranca: '0'.padStart(5, '0'),
            digitoVerificadorAgenciaCobranca: ''.padStart(1, ' '),
            especieTitulo: '03',
            aceiteTitulo: 'N',
            dtEmissaoTitulo: format(new Date(), 'ddMMyyyy'),
            codJurosMora: '1',
            dataJurosMora: ''.padStart(8, '0'),
            jurosMoraPorDia: '0.51'.replace('.', '').padStart(15, 0),
            codDesconto1: '0',
            dataDesconto1: ''.padStart(8, '0'),
            valorOuPercentualConcedido: '0'.padStart(15, 0),
            valorIofRecolhido: '0'.padStart(15, 0),
            valorAbatimento: '0'.padStart(15, 0),
            identificacaoTituloEmpresa: '0297899805907'.padStart(25, '0'),
            codigoParaProtesto: '3',
            numeroDiaProtesto: '00',
            codigoBaixaDevolucao: '1',
            numeroDiaBaixaDevolucao: '60'.padStart(3, '0'),
            codMoeda: '09',
            nrContrato: '0'.padStart(10, '0'),
            febrabanCnabExclusivo2: ' ',
        }

        const retorno = detalheLoteSegmentoP.concat(  
            obj.codigoBanco,
            obj.loteServicoHeaderArquivo,
            obj.tipoRegistro,
            obj.sequencialRegistroLote,
            obj.codSegmentoRegistroDetalhe,
            obj.febrabanCnabExclusivo,
            obj.codMovimentoRemessa,
            obj.codAgencia,
            obj.digitoVerificadorAgencia,
            obj.nrContaBancaria,
            obj.digitoVerificadorConta,
            obj.digitoVerificadorAgenciaConta,
            obj.nossoNumero,
            obj.codCarteira,
            obj.formaCadastroTituloBanco,
            obj.tipoDocumento,
            obj.tipoEmissaoBoletoPgto,
            obj.tipoDestribuicaoBoletoPgto,
            obj.nrIdentificacaoBoletoCobranca,
            obj.dtVencimentoTitulo,
            obj.valorNominalTitulo,
            obj.agenciaCobranca,
            obj.digitoVerificadorAgenciaCobranca,
            obj.especieTitulo,
            obj.aceiteTitulo,
            obj.dtEmissaoTitulo,
            obj.codJurosMora,
            obj.dataJurosMora,
            obj.jurosMoraPorDia,
            obj.codDesconto1,
            obj.dataDesconto1,
            obj.valorOuPercentualConcedido,
            obj.valorIofRecolhido,
            obj.valorAbatimento,
            obj.identificacaoTituloEmpresa,
            obj.codigoParaProtesto,
            obj.numeroDiaProtesto,
            obj.codigoBaixaDevolucao,
            obj.numeroDiaBaixaDevolucao,
            obj.codMoeda,
            obj.nrContrato,
            obj.febrabanCnabExclusivo2
        );

        return retorno
    }
}

module.exports = new CreateDetalheLoteSegmentoP();